### PR TITLE
Minor release fixes 0.3.1

### LINKED ISSUE #9: Bug: jinx_get_yesterday_timestamp() assumes GNU coreutils
### Expected Behavior

`jinx_get_yesterday_timestamp()` should return yesterday's timestamp on Linux.

### Actual Behavior

It won't work on systems where `date` command is provided by Busybox, such as on Alpine Linux (a distro commonly used for containers, among other things), because what's expected of `date` here is a GNU extension beyond what POSIX requires.

QEMU screenshot

### Steps to Reproduce the Problem

* boot up Alpine Linux
* try to use commands from `jinx_get_yesterday_timestamp()`

### Specifications

* **`jinx` version:** 0.3.1
* **OS and version:** Alpine Linux 3.8
* **nginx version:** n/a

### PR DESCRIPTION
**Pull request by click0**
### Proposed changes

* #7 
* Fix typo

### Resolved issue (if any)

Fixes #9 

### Additional notes

...

### CODE REVIEW

File: modules/30-jinx-helpers.sh [hunk 1]
```diff
@@ -33,12 +33,22 @@ fi
...
-    then
-        # for FreeBSD and, maybe, MacOS X
-        date -v -1d +%s
-    else
+    case $OSTYPE in
+        linux)
+            date +%s --date='-1 day'
+        ;;
+        alpine)
+            echo $(($(date +%s) - 86400))
```
Comment (Michcioperz) [inline modules/30-jinx-helpers.sh:40]: This version works just as well on GNU/Linux, and perhaps on all the platforms used. Wouldn't it be better to use it in all cases?

Comment (click0) [reply modules/30-jinx-helpers.sh:40]: Personally, I don’t like the mechanism of such a check at all, because during one day, the software can have several security fixes.
Probably, it is necessary to add the check frequency option to the jinx config. And the values of this variable: 0 - do not check and 24h - once a day, as now.
